parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Bulliby\UserTokenBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests,Controller,DependencyInjection,Event,Form,Resources}'
